version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgres_container
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=adminpassword
      - POSTGRESQL_DATABASE=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
    driver: local
